#!/usr/bin/perl -w
#
# Copyright (C) 2017 Giacomo Sanchietti
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use esmith::Build::CreateLinks  qw(:all);
use File::Path;

#--------------------------------------------------
# actions for nethserver-savapage-update event
#--------------------------------------------------

my $event = "nethserver-savapage-update";

event_templates($event, qw(
                 /etc/papersize
                 /opt/savapage/server/server.properties
                 /var/lib/machines/nsdc/etc/samba/smb.conf.include
));

event_actions($event, qw(
    initialize-default-databases  00
    nethserver-savapage-conf      10
    nethserver-savapage-conf-db   20
));

event_services($event, qw(
    postgresql reload
    savapage restart
));
