#!/usr/bin/bash

# wait 10 seconds to be sure savapage service is started
sleep 10

# allow self signed certs
/opt/savapage/server/bin/linux-x64/savapage-cmd --set-config-property --name auth.ldap.use-ssl.trust-self-signed --value Y

# sync AD/LDAP users
/opt/savapage/server/bin/linux-x64/savapage-cmd --sync-users-and-groups

# list users to see if synced - savapage-cmd --list-users
/opt/savapage/server/bin/linux-x64/savapage-cmd --list-users
